MicroFrontends/Company.WebUI/Models/CandidateDetailViewModel.cs
using System;

namespace Company.WebUI.Models
{
    public class CandidateDetailViewModel
    {
        public int IdCandidate { get; set; }
        public int IdVacancy { get; set; }
        public string Name { get; set; }
        public string Surname { get; set; }
        public string Email { get; set; }
        public DateTime InsertDate { get; set; }
    }
}

MicroFrontends/Company.WebUI/Models/CandidateListItemViewModel.cs
namespace Company.WebUI.Models
{
    public class CandidateListItemViewModel
    {
        public int IdCandidate { get; set; }
        public int IdVacancy { get; set; }
        public string Name { get; set; }
        public string Surname { get; set; }
    }
}

MicroFrontends/Company.WebUI/Models/Candidates/CandidateDetailViewModel.cs
using System;

namespace Company.WebUI.Models.Candidates;

public class CandidateDetailViewModel
{
    public Guid IdCandidate { get; set; }
    public long IdVacancy { get; set; }
    public string Name { get; set; }
    public string Surname { get; set; }
    public string Email { get; set; }
}

MicroFrontends/Company.WebUI/Models/Candidates/CandidateListItemViewModel.cs
using System;

namespace Company.WebUI.Models.Candidates;

public class CandidateListItemViewModel
{
    public Guid IdCandidate { get; set; }
    public long IdVacancy { get; set; }
    public string Name { get; set; }
    public string Surname { get; set; }
    public string Email { get; set; }
}

MicroFrontends/Company.WebUI/Models/VacancyDetailViewModel.cs
using System;

namespace Company.WebUI.Models
{
    public class VacancyDetailViewModel
    {
        public int IdVacancy { get; set; }
        public string Job { get; set; }
        public string Description { get; set; }
        public DateTime InsertDate { get; set; }
    }
}

MicroFrontends/Company.WebUI/Models/VacancyListItemViewModel.cs
namespace Company.WebUI.Models
{
    public class VacancyListItemViewModel
    {
        public int IdVacancy { get; set; }
        public string Job { get; set; }
        public string NumCandidates { get; set; }
    }
}

MicroFrontends/Company.WebUI/Models/Vancancies/VacancyDetailViewModel.cs
using System;

namespace Company.WebUI.Models.Vancancies
{
    public class VacancyDetailViewModel
    {
        public int IdVacancy { get; set; }
        public string Job { get; set; }
        public string Description { get; set; }
        public DateTime InsertDate { get; set; }
    }
}

MicroFrontends/Company.WebUI/Models/Vancancies/VacancyListItemViewModel.cs
namespace Company.WebUI.Models.Vancancies
{
    public class VacancyListItemViewModel
    {
        public int IdVacancy { get; set; }
        public string Job { get; set; }
        public string NumCandidates { get; set; }
    }
}

MicroFrontends/Company.WebUI/Controllers/CandidateController.cs
using System.Collections.Generic;
using System.Threading.Tasks;
using AutoMapper;
using Common.Client.Models.Candidate;
using Common.Client.Models.Vacancy;
using Common.Client.Services.Candidate;
using Company.WebUI.Models.Candidates;
using Microsoft.AspNetCore.Mvc;

namespace Company.WebUI.Controllers;

public class CandidateController : Controller
{
    private readonly ICandidateService _candidateService;
    private readonly IMapper _mapper;

    public CandidateController(
        ICandidateService candidateService,
        IMapper mapper)
    {
        _candidateService = candidateService ?? throw new System.ArgumentNullException(nameof(candidateService));
        _mapper = mapper ?? throw new System.ArgumentNullException(nameof(mapper));
    }

    [Route("candidates/{id}")]
    public async Task<IActionResult> Get(int id)
    {
        CandidateDetailResponse candidate = await _candidateService.GetAsync(id);
        CandidateDetailViewModel candidateDetailViewModel = _mapper.Map<CandidateDetailViewModel>(candidate);
        return View(candidateDetailViewModel);
    }

    [Route("candidates")]
    public async Task<IActionResult> List()
    {
        List<CandidateListItemResponse> candidates = await _candidateService.ListAsync();
        List<CandidateListItemViewModel> candidateListItemResponses = _mapper.Map<List<CandidateListItemViewModel>>(candidates);
        return View(candidateListItemResponses);
    }
}

MicroFrontends/Company.WebUI/Controllers/VacancyController.cs
using AutoMapper;
using Common.Client.Services.Vacancy;
using Microsoft.AspNetCore.Mvc;
using System.Collections.Generic;
using System.Threading.Tasks;
using Common.Client.Models.Vacancy;
using Company.WebUI.Models.Vancancies;

namespace Company.WebUI.Controllers
{
    public class VacancyController : Controller
    {
        private readonly IVacancyService _vacancyService;
        private readonly IMapper _mapper;

        public VacancyController(IVacancyService vacancyService, IMapper mapper)
        {
            _vacancyService = vacancyService ?? throw new System.ArgumentNullException(nameof(vacancyService));
            _mapper = mapper ?? throw new System.ArgumentNullException(nameof(mapper));
        }

        [Route("{id}")]
        public async Task<IActionResult> Get(int id)
        {
            VacancyDetailResponse vacancy = await _vacancyService.GetAsync(id);
            VacancyDetailViewModel vacancyDetailViewModel = _mapper.Map<VacancyDetailViewModel>(vacancy);
            return View(vacancyDetailViewModel);
        }

        [Route("")]
        public async Task<IActionResult> List()
        {
            List<VacancyListItemResponse> vacancies = await _vacancyService.ListAsync();
            List<VacancyListItemViewModel> vacancyListItemViewModels = _mapper.Map<List<VacancyListItemViewModel>>(vacancies);
            return View(vacancyListItemViewModels);
        }
    }
}

MicroFrontends/Company.WebUI/Views/Candidate/Get.cshtml
@model Company.WebUI.Models.Candidates.CandidateDetailViewModel

@{
    ViewData["Title"] = "Candidate Detail";
}

<h1>@ViewData["Title"]</h1>

<p><b>Job:</b> @Model.IdCandidate</p>
<p><b>ID:</b> @Model.IdVacancy</p>
<p><b>Name:</b> @Model.Name</p>
<p><b>Surname:</b> @Model.Surname</p>
<p><b>Email:</b> @Model.Email</p>

<br />

MicroFrontends/Company.WebUI/Views/Candidate/List.cshtml
@model List<Company.WebUI.Models.Candidates.CandidateListItemViewModel>

@{
    ViewData["Title"] = "Candidates List";
}

<h1>@ViewData["Title"]</h1>

<table class="table table-striped table-bordered table-hover" style="max-width: 500px;">
    <tr>
        <th>Id</th>
        <th>Name</th>
        <th>Surname</th>
        <th>Email</th>
    </tr>
    @foreach (var candidate in Model)
    {
        <tr>
            <td class="text-center">@candidate.IdCandidate</td>
            <td class="text-right">@candidate.Name</td>
            <td class="text-right">@candidate.Surname</td>
            <td class="text-right">@candidate.Email</td>
        </tr>
    }
</table>

MicroFrontends/Company.WebUI/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>@ViewData["Title"] - Company.WebUI</title>
    <link rel="stylesheet" href="~/lib/bootstrap/dist/css/bootstrap.min.css" />
    <link rel="stylesheet" href="~/css/site.css" />
</head>
<body>
    <header>
        <nav class="navbar navbar-expand-sm navbar-toggleable-sm navbar-light bg-white border-bottom box-shadow mb-3">
            <div class="container">
                <a class="navbar-brand" asp-area="" asp-controller="Home" asp-action="Index">Company.WebUI</a>
                <button class="navbar-toggler" type="button" data-toggle="collapse" data-target=".navbar-collapse" aria-controls="navbarSupportedContent"
                        aria-expanded="false" aria-label="Toggle navigation">
                    <span class="navbar-toggler-icon"></span>
                </button>
            </div>
        </nav>
    </header>
    <div class="container">
        <main role="main" class="pb-3">
            @RenderBody()
        </main>
    </div>
    <script src="~/lib/jquery/dist/jquery.min.js"></script>
    <script src="~/lib/bootstrap/dist/js/bootstrap.bundle.min.js"></script>
    <script src="~/js/site.js" asp-append-version="true"></script>
    @RenderSection("Scripts", required: false)
</body>
</html>

MicroFrontends/Company.WebUI/Views/Vacancy/Get.cshtml
@model Company.WebUI.Models.Vancancies.VacancyDetailViewModel

@{
    ViewData["Title"] = "Vacancy Detail";
}

<h1>@ViewData["Title"]</h1>

<p><b>ID:</b> @Model.IdVacancy</p>
<p><b>Job:</b> @Model.Job</p>
<p><b>Description:</b> @Model.Description</p>
<p><b>InsertDate:</b> @Model.InsertDate.ToString("dd-MM-yyyy")</p>

<br />

<p><a asp-controller="candidate" asp-action="List">View Candidates</a></p>

MicroFrontends/Company.WebUI/Views/Vacancy/List.cshtml
@model List<Company.WebUI.Models.Vancancies.VacancyListItemViewModel>

@{
    ViewData["Title"] = "Vacancies List";
}

<h1>@ViewData["Title"]</h1>

<table class="table table-striped table-bordered table-hover" style="max-width: 500px;">
    <tr>
        <th>Job</th>
        <th>Number Candidates</th>
        <th></th>
    </tr>
    @foreach (var vacancy in Model)
    {
        <tr>
            <td class="text-center">
                @vacancy.Job
            </td>
            <td class="text-right">
                @vacancy.NumCandidates
            </td>
            <td class="text-right">
                <a asp-controller="Vacancy" asp-action="Get" asp-route-id="@vacancy.IdVacancy">View Detail</a>
            </td>
        </tr>
    }
</table>